# Generated by Django 6.0.2 on 2026-02-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclExclCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incl_excl_categories',
            },
        ),
        migrations.CreateModel(
            name='InclusionExclusion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('inclusion', 'Inclusion'), ('exclusion', 'Exclusion')], max_length=10)),
                ('item_service', models.CharField(max_length=200)),
                ('details_notes', models.TextField(blank=True, null=True)),
                ('source_files', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inclusions.inclexclcategory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incl_excl', to='geography.country')),
            ],
            options={
                'db_table': 'inclusions_exclusions',
                'indexes': [models.Index(fields=['country', 'type', 'category'], name='inclusions__country_d90c9c_idx'), models.Index(fields=['country', 'type'], name='inclusions__country_bf07bc_idx'), models.Index(fields=['is_active'], name='inclusions__is_acti_381ef5_idx')],
            },
        ),
    ]
