# Generated by Django 6.0.2 on 2026-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='type',
            field=models.CharField(choices=[('INCLUSION', 'Inclusion'), ('EXCLUSION', 'Exclusion')], max_length=10),
        ),
    ]
