# Generated by Django 5.2.12 on 2026-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusions', '0002_alter_inclusionexclusion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusionexclusion',
            name='is_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inclusionexclusion',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('BUS', 'Bus'), ('TRAIN', 'Train')], max_length=20, null=True),
        ),
    ]
