# Generated by Django 6.0.2 on 2026-03-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_alter_region_code'),
        ('inclusions', '0002_alter_inclusionexclusion_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inclusionexclusion',
            index=models.Index(fields=['unique_code'], name='inclusions__unique__d4e810_idx'),
        ),
    ]
