# Generated by Django 5.2.12 on 2026-04-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusions', '0003_inclusionexclusion_is_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusionexclusion',
            name='is_transport',
        ),
        migrations.RemoveField(
            model_name='inclusionexclusion',
            name='transport_mode',
        ),
    ]
