# Generated by Django 6.0.2 on 2026-02-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('key_features_notes', models.TextField(blank=True, null=True)),
                ('source_citations', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='geography.region')),
            ],
            options={
                'db_table': 'attractions',
                'indexes': [models.Index(fields=['region', 'name', 'is_active'], name='attractions_region__f947c5_idx')],
            },
        ),
    ]
