# Generated by Django 6.0.2 on 2026-03-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image_url',
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/attraction_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractions.attraction')),
            ],
            options={
                'db_table': 'attraction_images',
                'indexes': [models.Index(fields=['attraction'], name='attraction__attract_f970dc_idx')],
            },
        ),
    ]
