# Generated by Django 6.0.2 on 2026-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_remove_attraction_image_url_attractionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=models.ImageField(upload_to='attraction_images/'),
        ),
    ]
