# Generated by Django 6.0.2 on 2026-03-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_alter_attractionimage_image'),
        ('geography', '0004_alter_region_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attraction',
            name='attractions_region__f947c5_idx',
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['reference_no', 'region', 'name', 'is_active'], name='attractions_referen_7dcb22_idx'),
        ),
    ]
