# Generated by Django 6.0.2 on 2026-02-23 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('day_tours', '0001_initial'),
        ('geography', '0001_initial'),
        ('inclusions', '0001_initial'),
        ('itinerary_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_number', models.CharField(max_length=20, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('total_nights', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('shared', 'Shared'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('share_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('based_on_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_plans', to='itinerary_templates.itinerarytemplate')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='geography.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='account.user')),
            ],
            options={
                'db_table': 'user_plans',
            },
        ),
        migrations.CreateModel(
            name='UserPlanDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('custom_itinerary_text', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_days', to='day_tours.daytour')),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='user_plans.userplan')),
            ],
            options={
                'db_table': 'user_plan_days',
            },
        ),
        migrations.CreateModel(
            name='UserPlanInclExcl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incl_excl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='inclusions.inclusionexclusion')),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incl_excl', to='user_plans.userplan')),
            ],
            options={
                'db_table': 'user_plan_incl_excl',
            },
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user', 'country', 'status', 'created_at'], name='user_plans_user_id_09ebf1_idx'),
        ),
        migrations.AddIndex(
            model_name='userplanday',
            index=models.Index(fields=['user_plan', 'day_tour'], name='user_plan_d_user_pl_e4bfd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplanday',
            constraint=models.UniqueConstraint(fields=('user_plan', 'day_number'), name='unique_plan_day'),
        ),
        migrations.AddIndex(
            model_name='userplaninclexcl',
            index=models.Index(fields=['user_plan', 'incl_excl'], name='user_plan_i_user_pl_f0e4b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplaninclexcl',
            constraint=models.UniqueConstraint(fields=('user_plan', 'incl_excl'), name='unique_plan_incl'),
        ),
    ]
