# Generated by Django 6.0.2 on 2026-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('SHARED', 'Shared'), ('ARCHIVED', 'Archived')], default='draft', max_length=20),
        ),
    ]
