# Generated by Django 6.0.2 on 2026-03-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_remove_country_images_remove_region_images_and_more'),
        ('itinerary_templates', '0004_remove_itinerarytemplate_unique_default_template_per_country_days_and_more'),
        ('user_plans', '0002_alter_userplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanday',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_days', to='geography.region'),
        ),
        migrations.AddField(
            model_name='userplanday',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_days_using', to='itinerary_templates.itinerarytemplate'),
        ),
    ]
