# Generated by Django 4.2.7 on 2026-03-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0009_remove_daytour_travel_type'),
        ('user_plans', '0003_userplanday_region_userplanday_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanday',
            name='day_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_days', to='day_tours.daytour'),
        ),
    ]
