# Generated by Django 4.2.7 on 2026-03-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_image_url_hotelimage'),
        ('user_plans', '0004_alter_userplanday_day_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanday',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel for overnight stay on this day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_days', to='hotel.hotel'),
        ),
    ]
