# Generated by Django 5.2.12 on 2026-04-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0012_daytour_slot'),
        ('geography', '0003_remove_country_images_remove_region_images_and_more'),
        ('hotel', '0005_hotel_price_currency_add_chf'),
        ('itinerary_templates', '0006_remove_itinerarytemplateday_itinerary_t_templat_8eec4b_idx_and_more'),
        ('user_plans', '0005_userplanday_hotel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userplanday',
            name='user_plan_d_user_pl_e4bfd6_idx',
        ),
        migrations.RemoveField(
            model_name='userplanday',
            name='day_tour',
        ),
        migrations.AddField(
            model_name='userplanday',
            name='morning_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_morning_days', to='day_tours.daytour'),
        ),
        migrations.AddField(
            model_name='userplanday',
            name='night_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_night_days', to='day_tours.daytour'),
        ),
        migrations.AddField(
            model_name='userplanday',
            name='noon_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_noon_days', to='day_tours.daytour'),
        ),
        migrations.AddIndex(
            model_name='userplanday',
            index=models.Index(fields=['user_plan', 'morning_tour', 'noon_tour', 'night_tour'], name='user_plan_d_user_pl_4e9dd3_idx'),
        ),
    ]
