# Generated by Django 5.2.12 on 2026-04-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusions', '0003_inclusionexclusion_is_transport_and_more'),
        ('user_plans', '0006_remove_userplanday_user_plan_d_user_pl_e4bfd6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanday',
            name='morning_to_noon_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_morning_to_noon_transport', to='inclusions.inclusionexclusion'),
        ),
        migrations.AddField(
            model_name='userplanday',
            name='noon_to_night_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_noon_to_night_transport', to='inclusions.inclusionexclusion'),
        ),
    ]
