# Generated by Django 6.0.2 on 2026-03-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_country_images_region_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='images',
        ),
        migrations.RemoveField(
            model_name='region',
            name='images',
        ),
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_images', to='geography.country')),
            ],
            options={
                'db_table': 'country_images',
                'indexes': [models.Index(fields=['country'], name='country_ima_country_be613e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='region/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_images', to='geography.region')),
            ],
            options={
                'db_table': 'region_images',
                'indexes': [models.Index(fields=['region'], name='region_imag_region__bfa6e0_idx')],
            },
        ),
    ]
