# Generated by Django 6.0.2 on 2026-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_remove_country_images_remove_region_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
