# Generated by Django 6.0.2 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_remove_country_images_remove_region_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='has_airport',
            field=models.BooleanField(default=False),
        ),
    ]
