# Generated by Django 6.0.2 on 2026-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin'), ('basic_user', 'Basic User')], default='basic_user', max_length=20),
        ),
    ]
