# Generated by Django 6.0.2 on 2026-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin'), ('BASIC_USER', 'Basic User')], default='AGENT', max_length=20),
        ),
    ]
