# Generated by Django 6.0.2 on 2026-03-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
