# Generated by Django 6.0.2 on 2026-02-23 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('attractions', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_code', models.CharField(max_length=20, unique=True)),
                ('activity_combination', models.CharField(max_length=500)),
                ('est_time_distance', models.CharField(blank=True, max_length=200, null=True)),
                ('overnight_location', models.CharField(blank=True, max_length=150, null=True)),
                ('source_file', models.CharField(blank=True, max_length=200, null=True)),
                ('itinerary_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_day_tours', to='account.user')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_tours', to='geography.region')),
            ],
            options={
                'db_table': 'day_tours',
            },
        ),
        migrations.CreateModel(
            name='DayTourAttraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_order', models.IntegerField(default=1)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_tours', to='attractions.attraction')),
                ('day_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_attractions', to='day_tours.daytour')),
            ],
            options={
                'db_table': 'day_tour_attractions',
            },
        ),
        migrations.AddIndex(
            model_name='daytour',
            index=models.Index(fields=['region', 'overnight_location', 'is_active', 'created_by'], name='day_tours_region__dca466_idx'),
        ),
        migrations.AddIndex(
            model_name='daytourattraction',
            index=models.Index(fields=['day_tour'], name='day_tour_at_day_tou_ec484b_idx'),
        ),
        migrations.AddIndex(
            model_name='daytourattraction',
            index=models.Index(fields=['attraction'], name='day_tour_at_attract_e91f76_idx'),
        ),
        migrations.AddConstraint(
            model_name='daytourattraction',
            constraint=models.UniqueConstraint(fields=('day_tour', 'attraction'), name='unique_daytour_attraction'),
        ),
    ]
