# Generated by Django 6.0.2 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytour',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('GROUP', 'Group Tour'), ('SOLO', 'Solo Travel'), ('COUPLE', 'Couple'), ('GENERAL', 'General')], max_length=20, null=True),
        ),
    ]
