# Generated by Django 6.0.2 on 2026-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0002_daytour_travel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytour',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daytour',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daytour',
            name='validity_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='daytour',
            name='travel_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
