# Generated by Django 6.0.2 on 2026-03-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0003_daytour_valid_from_daytour_valid_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytour',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='daytour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
