# Generated by Django 6.0.2 on 2026-03-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0004_daytour_currency_daytour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytour',
            name='default_day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daytour',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
