# Generated by Django 6.0.2 on 2026-03-03 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0005_daytour_default_day_number_daytour_is_default'),
        ('geography', '0002_country_images_region_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='daytour',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('region', 'default_day_number'), name='unique_default_per_day_per_region'),
        ),
    ]
