# Generated by Django 6.0.2 on 2026-03-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0006_daytour_unique_default_per_day_per_region'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='daytour',
            name='unique_default_per_day_per_region',
        ),
        migrations.RemoveField(
            model_name='daytour',
            name='default_day_number',
        ),
        migrations.RemoveField(
            model_name='daytour',
            name='is_default',
        ),
    ]
