# Generated by Django 4.2.7 on 2026-03-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0007_remove_daytour_unique_default_per_day_per_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytour',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('GROUP', 'Group Tour'), ('SOLO', 'Solo Travel'), ('COUPLE', 'Couple')], max_length=20, null=True),
        ),
    ]
