# Generated by Django 6.0.2 on 2026-03-05 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0007_remove_daytour_unique_default_per_day_per_region_and_more'),
        ('geography', '0004_alter_region_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='daytour',
            name='day_tours_region__dca466_idx',
        ),
        migrations.AddIndex(
            model_name='daytour',
            index=models.Index(fields=['region', 'unique_code', 'overnight_location', 'is_active', 'created_by'], name='day_tours_region__cf92cb_idx'),
        ),
    ]
