# Generated by Django 4.2.7 on 2026-03-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0008_remove_general_travel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytour',
            name='travel_type',
        ),
    ]
