# Generated by Django 4.2.7 on 2026-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0009_remove_daytour_travel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytour',
            name='includes_night',
            field=models.BooleanField(default=False, help_text='Whether this day tour includes an overnight stay.'),
        ),
        migrations.AddField(
            model_name='daytour',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default day tour for the region.'),
        ),
    ]
