# Generated by Django 4.2.7 on 2026-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0010_add_includes_night_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytour',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('ISK', 'Icelandic Króna'), ('CHF', 'Swiss Franc')], default='INR', max_length=10),
        ),
    ]
