# Generated by Django 5.2.12 on 2026-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0011_add_isk_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytour',
            name='slot',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('NOON', 'Noon'), ('NIGHT', 'Night'), ('FULL_DAY', 'Full Day')], default='FULL_DAY', max_length=20),
        ),
    ]
