# Generated by Django 6.0.2 on 2026-02-23 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('day_tours', '0001_initial'),
        ('geography', '0001_initial'),
        ('inclusions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('total_nights', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='geography.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to='account.user')),
            ],
            options={
                'db_table': 'itinerary_templates',
            },
        ),
        migrations.CreateModel(
            name='ItineraryTemplateDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('custom_notes', models.TextField(blank=True, null=True)),
                ('is_arrival_day', models.BooleanField(default=False)),
                ('is_departure_day', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('day_tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_days', to='day_tours.daytour')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary_templates.itinerarytemplate')),
            ],
            options={
                'db_table': 'itinerary_template_days',
            },
        ),
        migrations.CreateModel(
            name='ItineraryTemplateInclExcl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incl_excl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='inclusions.inclusionexclusion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incl_excl', to='itinerary_templates.itinerarytemplate')),
            ],
            options={
                'db_table': 'itinerary_template_incl_excl',
            },
        ),
        migrations.AddIndex(
            model_name='itinerarytemplate',
            index=models.Index(fields=['country', 'is_active', 'created_by'], name='itinerary_t_country_6930dd_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytemplateday',
            index=models.Index(fields=['template', 'day_tour'], name='itinerary_t_templat_8eec4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerarytemplateday',
            constraint=models.UniqueConstraint(fields=('template', 'day_number'), name='unique_template_day'),
        ),
        migrations.AddIndex(
            model_name='itinerarytemplateinclexcl',
            index=models.Index(fields=['template', 'incl_excl'], name='itinerary_t_templat_ccd69a_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerarytemplateinclexcl',
            constraint=models.UniqueConstraint(fields=('template', 'incl_excl'), name='unique_template_incl'),
        ),
    ]
