# Generated by Django 6.0.2 on 2026-03-03 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_country_images_region_images'),
        ('itinerary_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarytemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='itinerarytemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('country', 'total_days'), name='unique_default_template_per_country_days'),
        ),
    ]
