# Generated by Django 4.2.7 on 2026-03-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_templates', '0002_itinerarytemplate_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarytemplate',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('COUPLE', 'Couple'), ('GROUP', 'Group'), ('SOLO', 'Solo')], max_length=10, null=True),
        ),
    ]
