# Generated by Django 6.0.2 on 2026-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_templates', '0002_itinerarytemplate_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarytemplate',
            name='total_days',
            field=models.IntegerField(blank=True, default=1, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='itinerarytemplate',
            name='total_nights',
            field=models.IntegerField(blank=True, default=1, editable=False, null=True),
        ),
    ]
