# Generated by Django 6.0.2 on 2026-03-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_remove_country_images_remove_region_images_and_more'),
        ('itinerary_templates', '0003_add_travel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itinerarytemplate',
            name='unique_default_template_per_country_days',
        ),
        migrations.AddField(
            model_name='itinerarytemplate',
            name='includes_night',
            field=models.BooleanField(default=False, help_text='If True, this template includes an overnight stay (1D/1N). If False, it is a day tour only (1D/0N).'),
        ),
        migrations.AddField(
            model_name='itinerarytemplate',
            name='region',
            field=models.ForeignKey(blank=True, help_text='City/region this single-day template belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='geography.region'),
        ),
        migrations.AlterField(
            model_name='itinerarytemplate',
            name='total_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itinerarytemplate',
            name='total_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='itinerarytemplate',
            index=models.Index(fields=['region', 'is_default', 'is_active'], name='itinerary_t_region__92e026_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerarytemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('region__isnull', False)), fields=('region',), name='unique_default_template_per_region'),
        ),
    ]
