# Generated by Django 4.2.7 on 2026-03-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0009_remove_daytour_travel_type'),
        ('itinerary_templates', '0004_remove_itinerarytemplate_unique_default_template_per_country_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarytemplateday',
            name='day_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_days', to='day_tours.daytour'),
        ),
    ]
