# Generated by Django 5.2.12 on 2026-04-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_tours', '0012_daytour_slot'),
        ('itinerary_templates', '0005_alter_itinerarytemplateday_day_tour'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itinerarytemplateday',
            name='itinerary_t_templat_8eec4b_idx',
        ),
        migrations.RemoveField(
            model_name='itinerarytemplateday',
            name='day_tour',
        ),
        migrations.AddField(
            model_name='itinerarytemplateday',
            name='morning_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_morning_days', to='day_tours.daytour'),
        ),
        migrations.AddField(
            model_name='itinerarytemplateday',
            name='night_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_night_days', to='day_tours.daytour'),
        ),
        migrations.AddField(
            model_name='itinerarytemplateday',
            name='noon_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_noon_days', to='day_tours.daytour'),
        ),
        migrations.AddIndex(
            model_name='itinerarytemplateday',
            index=models.Index(fields=['template', 'morning_tour', 'noon_tour', 'night_tour'], name='itinerary_t_templat_fcf698_idx'),
        ),
    ]
