# Generated by Django 5.2.12 on 2026-04-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusions', '0003_inclusionexclusion_is_transport_and_more'),
        ('itinerary_templates', '0006_remove_itinerarytemplateday_itinerary_t_templat_8eec4b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarytemplateday',
            name='morning_to_noon_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_morning_to_noon_transport', to='inclusions.inclusionexclusion'),
        ),
        migrations.AddField(
            model_name='itinerarytemplateday',
            name='noon_to_night_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_noon_to_night_transport', to='inclusions.inclusionexclusion'),
        ),
    ]
