# Generated by Django 5.2.12 on 2026-04-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_templates', '0007_itinerarytemplateday_morning_to_noon_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarytemplateday',
            name='morning_to_noon_transport',
        ),
        migrations.RemoveField(
            model_name='itinerarytemplateday',
            name='noon_to_night_transport',
        ),
    ]
