# Generated by Django 4.2.7 on 2026-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_image_url_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Numeric price per night for calculations', max_digits=10),
        ),
    ]
